In [ ]:
import os
from PIL import Image

def check_images(directory):
    for file_name in os.listdir(directory):
        file_path = os.path.join(directory, file_name)
        try:
            with Image.open(file_path) as img:
                img.verify()  # Verify that the file is a valid image
        except (IOError, SyntaxError) as e:
            print(f"Corrupted file: {file_path}")

check_images(r"/content/extracted_files/dataset_new/msumsfd_gfacnn/attack")
check_images(r"/content/extracted_files/dataset_new/msumsfd_gfacnn/real")


In [3]:
# Install gdown if not already installed
!pip install gdown

# Download the zip file from Google Drive
import gdown
import zipfile

# Google Drive URL with file id for direct download
#url = 'https://drive.google.com/uc?id=1FwQ1lI2Btbzv2ksIVrcC1P2YSotyDeMd&export=download'
url = 'https://drive.google.com/uc?export=download&id=11kd0T-jJf72f4Jx6ioKRt1tWupxWaupg'
output = 'file.zip'

# Download the file
gdown.download(url, output, quiet=False)

# Unzip the file
with zipfile.ZipFile(output, 'r') as zip_ref:
    zip_ref.extractall('extracted_files')

print("File downloaded and unzipped successfully.")


Downloading...
From (original): https://drive.google.com/uc?export=download&id=11kd0T-jJf72f4Jx6ioKRt1tWupxWaupg
From (redirected): https://drive.google.com/uc?export=download&id=11kd0T-jJf72f4Jx6ioKRt1tWupxWaupg&confirm=t&uuid=b28f6509-3bea-4ad8-aa75-2f733c91647e
To: /content/file.zip
100%|██████████| 217M/217M [00:09<00:00, 22.8MB/s]


File downloaded and unzipped successfully.


In [5]:
import os
import random
import yaml
import tensorflow as tf
from sklearn import preprocessing
from sklearn.utils import shuffle
from tqdm import tqdm


class Dataset:
    def __init__(self, name, batch_size, attack_dir, real_dir):  # Fixed __init__
        self.name = name
        self.batch_size = batch_size
        self.attack_dir = attack_dir
        self.real_dir = real_dir
        self.dataset = MsuMsfdDataset(batch_size, attack_dir, real_dir)

        file_path, label_truth = self.dataset.load_idx()

        # Encode the labels
        self.encoding_truth = preprocessing.LabelEncoder()
        self.encoding_truth.fit(label_truth)
        self.list_label_truth = self.encoding_truth.transform(label_truth)

        self.list_file_path_truth = file_path.copy()

        self.shuffle_dataset()
        self.len_dataset = len(self.list_file_path_truth)


        self.standard_img_size = 224

        # Build dataset using tf.data for better performance
        self.train_dataset = self.build_tf_dataset()

    def shuffle_dataset(self):
        self.list_file_path_truth, self.list_label_truth = shuffle(self.list_file_path_truth, self.list_label_truth,
                                                                   random_state=10)
    def load_and_preprocess_image(self, file_path, label):
        img = tf.io.read_file(file_path)

        # Extract the file extension
        file_extension = tf.strings.substr(file_path, -4, 4)  # Get the last 4 characters

        # Check if the file is a JPEG or PNG
        is_jpg = tf.strings.regex_full_match(file_extension, '.jpg|.jpeg')
        is_png = tf.strings.regex_full_match(file_extension, '.png')

        # Define the image decoding function based on the file extension
        def decode_jpeg_image():
            img_decoded = tf.image.decode_jpeg(img, channels=3)
            img_resized = tf.image.resize(img_decoded, [self.standard_img_size, self.standard_img_size])
            return tf.image.convert_image_dtype(img_resized, dtype=tf.float32)

        def decode_png_image():
            img_decoded = tf.image.decode_png(img, channels=3)
            img_resized = tf.image.resize(img_decoded, [self.standard_img_size, self.standard_img_size])
            return tf.image.convert_image_dtype(img_resized, dtype=tf.float32)

        def skip_image():
            # Handle the case where the image format is not supported
            img_placeholder = tf.zeros([self.standard_img_size, self.standard_img_size, 3], dtype=tf.uint8)
            return tf.image.convert_image_dtype(img_placeholder, dtype=tf.float32)

        # Conditionally decode the image based on its extension
        img = tf.cond(is_jpg, decode_jpeg_image,
                      lambda: tf.cond(is_png, decode_png_image, skip_image))

        return img, label

    def augment_image(self, img, label):
        # Apply random flipping, brightness changes, etc.
        img = tf.image.random_flip_left_right(img)
        img = tf.image.random_brightness(img, 0.1)
        return img, label

    def build_tf_dataset(self):
        # Create dataset from file paths and labels
        dataset = tf.data.Dataset.from_tensor_slices((self.list_file_path_truth, self.list_label_truth))
        dataset = dataset.shuffle(buffer_size=self.len_dataset)  # Shuffle dataset
        dataset = dataset.map(self.load_and_preprocess_image, num_parallel_calls=2)  # Load images
        dataset = dataset.map(self.augment_image, num_parallel_calls=2)  # Data augmentation
        dataset = dataset.batch(self.batch_size)  # Batch the data
        dataset = dataset.prefetch(buffer_size=2)  # Prefetch for optimal performance
        return dataset

    def generate_minibatch(self):
        start_idx = 0
        total_batches = (self.len_dataset + self.batch_size - 1) // self.batch_size
        print("Using tf.data pipeline for minibatch generation")

        with tqdm(total=total_batches, desc="Generating Minibatches", unit="batch") as pbar:
            for batch in self.train_dataset:
                batch_img_4_truth, batch_label_truth = batch

                # Select random images for LPC loss
                batch_random_1 = []
                batch_random_2 = []
                list_random_images_path1 = random.sample(self.list_file_path_truth, k=len(batch_img_4_truth))
                list_random_images_path2 = random.sample(self.list_file_path_truth, k=len(batch_img_4_truth))

                for file_path_1 in list_random_images_path1:
                    img1 = self.load_and_preprocess_image(file_path_1, None)[0]
                    batch_random_1.append(img1)

                for file_path_2 in list_random_images_path2:
                    img2 = self.load_and_preprocess_image(file_path_2, None)[0]
                    batch_random_2.append(img2)

                batch_img_random_1 = tf.stack(batch_random_1)
                batch_img_random_2 = tf.stack(batch_random_2)
                batch_label_random = tf.zeros(len(batch_img_random_1), dtype=tf.float32)

                start_idx += self.batch_size
                pbar.update(1)
                yield batch_img_4_truth, batch_label_truth, batch_img_random_1, batch_img_random_2, batch_label_random


class MsuMsfdDataset:
    def __init__(self, batch_size, attack_dir, real_dir):  # Fixed __init__
        self.batch_size = batch_size
        self.attack_dir = attack_dir
        self.real_dir = real_dir

    def load_idx(self):
        list_file_path = []
        list_label_truth = []
        attack_dir = self.attack_dir
        real_dir = self.real_dir

        print('Loading index for attack samples...')
        for pic in os.listdir(attack_dir):
            list_file_path.append(os.path.join(attack_dir, pic))
            list_label_truth.append('attack')

        print('Loading index for real samples...')
        for pic in os.listdir(real_dir):
            list_file_path.append(os.path.join(real_dir, pic))
            list_label_truth.append('real')

        return list_file_path, list_label_truth

if __name__ == '__main__':
    msumsfd_dataset = Dataset('replayattack', 32, attack_dir=r"/content/extracted_files/dataset_small/msumsfd_gfacnn/attack",
                              real_dir=r"/content/extracted_files/dataset_small/msumsfd_gfacnn/real")

    for img_4_truth, label_truth, img_random_1, img_random_2, label_random in msumsfd_dataset.generate_minibatch():
        print(label_truth)

    # msumsfd_dataset = Dataset('replayattack', 32, attack_dir=r"/content/extracted_files/dataset_new/msumsfd_gfacnn/attack",
    #                           real_dir=r"/content/extracted_files/dataset_new/msumsfd_gfacnn/real")

    # img_4_truth, label_truth, img_random_1, img_random_2, label_random = msumsfd_dataset.generate_minibatch()

    # # Debugging: Save the images and plot them
    # for i, img in enumerate(img_4_truth[:4]):  # Save only first 4 images for debugging
    #     path = os.path.join('debug_as', f'img_{i}.jpg')
    #     cv2.imwrite(path, cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

    # h, w = 10, 10  # for raster image
    # nrows, ncols = 2, 2  # array of sub-plots
    # figsize = [6, 8]
    # fig, ax = plt.subplots(nrows=nrows, ncols=ncols, figsize=figsize)

    # # plot simple raster image on each sub-plot
    # for i, axi in enumerate(ax.flat):
    #     img = img_4_truth[i]
    #     axi.imshow(img)
    #     axi.set_title(label_truth[i])

    # plt.tight_layout()
    # plt.show()

Loading index for attack samples...
Loading index for real samples...
Using tf.data pipeline for minibatch generation


Generating Minibatches:   3%|▎         | 1/36 [00:00<00:29,  1.19batch/s]

tf.Tensor([1 0 0 0 0 1 0 0 1 0 1 1 0 1 0 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   6%|▌         | 2/36 [00:01<00:19,  1.73batch/s]

tf.Tensor([0 1 0 1 1 1 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:   8%|▊         | 3/36 [00:01<00:15,  2.10batch/s]

tf.Tensor([1 1 1 0 1 0 0 0 1 1 1 0 1 1 1 1 0 0 1 0 0 1 1 0 0 0 0 1 0 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  11%|█         | 4/36 [00:01<00:13,  2.31batch/s]

tf.Tensor([1 0 0 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 1 1 1 1 1 0 0 1 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  14%|█▍        | 5/36 [00:02<00:12,  2.43batch/s]

tf.Tensor([1 0 1 0 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  17%|█▋        | 6/36 [00:02<00:13,  2.20batch/s]

tf.Tensor([0 0 1 0 0 1 1 1 0 1 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 1 0 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  19%|█▉        | 7/36 [00:03<00:12,  2.35batch/s]

tf.Tensor([1 1 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1 1 0 0 0 1 1 1 0 0 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  22%|██▏       | 8/36 [00:03<00:11,  2.49batch/s]

tf.Tensor([0 0 0 0 0 0 1 1 1 1 0 1 0 1 0 1 1 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  25%|██▌       | 9/36 [00:03<00:10,  2.60batch/s]

tf.Tensor([0 0 1 0 1 1 1 1 0 1 0 1 0 0 0 1 1 1 0 1 0 0 0 1 0 1 0 1 0 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  28%|██▊       | 10/36 [00:04<00:09,  2.66batch/s]

tf.Tensor([0 0 1 0 0 0 1 0 0 0 1 1 1 0 0 1 1 0 1 1 0 0 1 1 1 0 1 0 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  31%|███       | 11/36 [00:04<00:09,  2.71batch/s]

tf.Tensor([1 1 0 0 0 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  33%|███▎      | 12/36 [00:04<00:08,  2.74batch/s]

tf.Tensor([1 0 1 1 0 1 0 1 0 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 1 1 0 1 1 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  36%|███▌      | 13/36 [00:05<00:08,  2.74batch/s]

tf.Tensor([0 0 0 0 1 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 1 0 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  39%|███▉      | 14/36 [00:05<00:07,  2.76batch/s]

tf.Tensor([0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 0 1 1 0 0 0 1 1 1 1 1 0 0 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  42%|████▏     | 15/36 [00:06<00:07,  2.83batch/s]

tf.Tensor([0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  44%|████▍     | 16/36 [00:06<00:07,  2.85batch/s]

tf.Tensor([1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 0 0 1 0 1 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  47%|████▋     | 17/36 [00:06<00:06,  2.86batch/s]

tf.Tensor([0 0 1 1 0 1 0 1 1 0 1 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  50%|█████     | 18/36 [00:07<00:06,  2.88batch/s]

tf.Tensor([0 1 1 0 1 1 0 1 0 1 0 0 1 0 1 1 0 1 0 0 1 0 1 1 1 0 1 1 1 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  53%|█████▎    | 19/36 [00:07<00:05,  2.85batch/s]

tf.Tensor([0 1 1 0 0 0 0 0 0 0 1 1 1 0 1 1 1 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  56%|█████▌    | 20/36 [00:07<00:05,  2.87batch/s]

tf.Tensor([0 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 0 1 0 0 1 0 1 0 0 1 0 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  58%|█████▊    | 21/36 [00:08<00:05,  2.91batch/s]

tf.Tensor([1 0 1 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  61%|██████    | 22/36 [00:08<00:04,  2.88batch/s]

tf.Tensor([0 0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  64%|██████▍   | 23/36 [00:08<00:04,  2.79batch/s]

tf.Tensor([1 1 1 1 0 1 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  67%|██████▋   | 24/36 [00:09<00:04,  2.56batch/s]

tf.Tensor([1 1 1 0 1 1 1 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  69%|██████▉   | 25/36 [00:09<00:04,  2.31batch/s]

tf.Tensor([1 0 1 1 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 1 1 1 0 1 1 1 0 0 1 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  72%|███████▏  | 26/36 [00:10<00:04,  2.08batch/s]

tf.Tensor([1 0 0 1 0 0 1 0 1 1 1 0 0 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  75%|███████▌  | 27/36 [00:10<00:04,  2.01batch/s]

tf.Tensor([1 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  78%|███████▊  | 28/36 [00:11<00:04,  1.93batch/s]

tf.Tensor([0 1 1 1 0 1 0 0 1 0 1 1 0 0 0 0 1 1 1 0 1 0 0 0 0 1 1 1 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  81%|████████  | 29/36 [00:12<00:03,  1.91batch/s]

tf.Tensor([1 1 0 1 1 0 1 1 0 0 0 0 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  83%|████████▎ | 30/36 [00:12<00:03,  1.80batch/s]

tf.Tensor([0 0 0 0 0 0 0 0 1 0 1 0 1 1 1 0 1 0 1 0 1 1 0 1 0 1 0 0 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  86%|████████▌ | 31/36 [00:13<00:02,  1.82batch/s]

tf.Tensor([0 0 0 1 1 0 1 0 1 0 1 0 0 0 1 1 0 1 0 1 0 1 0 1 1 0 1 1 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  89%|████████▉ | 32/36 [00:13<00:02,  1.93batch/s]

tf.Tensor([0 0 0 1 1 1 0 1 1 1 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  92%|█████████▏| 33/36 [00:14<00:01,  2.06batch/s]

tf.Tensor([0 0 0 1 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 1 0 1 0 1 0 1 0 0 1 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  94%|█████████▍| 34/36 [00:14<00:00,  2.17batch/s]

tf.Tensor([0 1 1 0 1 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches: 100%|██████████| 36/36 [00:15<00:00,  2.88batch/s]

tf.Tensor([1 0 0 0 0 0 1 0 1 1 0 0 0 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 0], shape=(32,), dtype=int64)
tf.Tensor([0 1 1 1 0 0 0 0], shape=(8,), dtype=int64)


Generating Minibatches: 100%|██████████| 36/36 [00:20<00:00,  1.75batch/s]


In [ ]:
import os
import random
import yaml
import tensorflow as tf
from sklearn import preprocessing
from sklearn.utils import shuffle
from tqdm import tqdm


class Dataset:
    def __init__(self, name, batch_size, attack_dir, real_dir):  # Fixed __init__
        self.name = name
        self.batch_size = batch_size
        self.attack_dir = attack_dir
        self.real_dir = real_dir
        self.dataset = MsuMsfdDataset(batch_size, attack_dir, real_dir)

        file_path, label_truth = self.dataset.load_idx()

        # Encode the labels
        self.encoding_truth = preprocessing.LabelEncoder()
        self.encoding_truth.fit(label_truth)
        self.list_label_truth = self.encoding_truth.transform(label_truth)

        self.list_file_path_truth = file_path.copy()

        self.shuffle_dataset()
        self.len_dataset = len(self.list_file_path_truth)


        self.standard_img_size = 224

        # Build dataset using tf.data for better performance
        self.train_dataset = self.build_tf_dataset()

    def shuffle_dataset(self):
        self.list_file_path_truth, self.list_label_truth = shuffle(self.list_file_path_truth, self.list_label_truth,
                                                                   random_state=10)
    def load_and_preprocess_image(self, file_path, label):
            try:
                img = tf.io.read_file(file_path)
                img = tf.image.decode_jpeg(img, channels=3)
                img = tf.image.resize(img, (self.standard_img_size, self.standard_img_size))
                img = img / 255.0  # Normalize to [0, 1]
                return img, label
            except tf.errors.InvalidArgumentError:
                print(f"Error decoding image akash: {file_path}")
                # Handle the error, e.g., by skipping the image or using a placeholder
                return tf.zeros((self.standard_img_size, self.standard_img_size, 3)), label

    def augment_image(self, img, label):
        # Apply random flipping, brightness changes, etc.
        img = tf.image.random_flip_left_right(img)
        img = tf.image.random_brightness(img, 0.1)
        return img, label

    def build_tf_dataset(self):
        # Create dataset from file paths and labels
        dataset = tf.data.Dataset.from_tensor_slices((self.list_file_path_truth, self.list_label_truth))
        dataset = dataset.shuffle(buffer_size=self.len_dataset)  # Shuffle dataset
        dataset = dataset.map(self.load_and_preprocess_image, num_parallel_calls=2)  # Load images
        dataset = dataset.map(self.augment_image, num_parallel_calls=2)  # Data augmentation
        dataset = dataset.batch(self.batch_size)  # Batch the data
        dataset = dataset.prefetch(buffer_size=2)  # Prefetch for optimal performance
        return dataset

    def generate_minibatch(self):
        start_idx = 0
        total_batches = (self.len_dataset + self.batch_size - 1) // self.batch_size
        print("Using tf.data pipeline for minibatch generation")

        with tqdm(total=total_batches, desc="Generating Minibatches", unit="batch") as pbar:
            for batch in self.train_dataset:
                batch_img_4_truth, batch_label_truth = batch

                # Select random images for LPC loss
                batch_random_1 = []
                batch_random_2 = []
                list_random_images_path1 = random.sample(self.list_file_path_truth, k=len(batch_img_4_truth))
                list_random_images_path2 = random.sample(self.list_file_path_truth, k=len(batch_img_4_truth))

                for file_path_1 in list_random_images_path1:
                    img1 = self.load_and_preprocess_image(file_path_1, None)[0]
                    batch_random_1.append(img1)

                for file_path_2 in list_random_images_path2:
                    img2 = self.load_and_preprocess_image(file_path_2, None)[0]
                    batch_random_2.append(img2)

                batch_img_random_1 = tf.stack(batch_random_1)
                batch_img_random_2 = tf.stack(batch_random_2)
                batch_label_random = tf.zeros(len(batch_img_random_1), dtype=tf.float32)

                start_idx += self.batch_size
                pbar.update(1)
                yield batch_img_4_truth, batch_label_truth, batch_img_random_1, batch_img_random_2, batch_label_random


class MsuMsfdDataset:
    def __init__(self, batch_size, attack_dir, real_dir):  # Fixed __init__
        self.batch_size = batch_size
        self.attack_dir = attack_dir
        self.real_dir = real_dir

    def load_idx(self):
        list_file_path = []
        list_label_truth = []
        attack_dir = self.attack_dir
        real_dir = self.real_dir

        print('Loading index for attack samples...')
        for pic in os.listdir(attack_dir):
            list_file_path.append(os.path.join(attack_dir, pic))
            list_label_truth.append('attack')

        print('Loading index for real samples...')
        for pic in os.listdir(real_dir):
            list_file_path.append(os.path.join(real_dir, pic))
            list_label_truth.append('real')

        return list_file_path, list_label_truth

if __name__ == '__main__':
    msumsfd_dataset = Dataset('replayattack', 32, attack_dir=r"/content/extracted_files/dataset_new/msumsfd_gfacnn/attack",
                              real_dir=r"/content/extracted_files/dataset_new/msumsfd_gfacnn/real")

    for img_4_truth, label_truth, img_random_1, img_random_2, label_random in msumsfd_dataset.generate_minibatch():
        print(label_truth)

    # msumsfd_dataset = Dataset('replayattack', 32, attack_dir=r"/content/extracted_files/dataset_new/msumsfd_gfacnn/attack",
    #                           real_dir=r"/content/extracted_files/dataset_new/msumsfd_gfacnn/real")

    # img_4_truth, label_truth, img_random_1, img_random_2, label_random = msumsfd_dataset.generate_minibatch()

    # # Debugging: Save the images and plot them
    # for i, img in enumerate(img_4_truth[:4]):  # Save only first 4 images for debugging
    #     path = os.path.join('debug_as', f'img_{i}.jpg')
    #     cv2.imwrite(path, cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

    # h, w = 10, 10  # for raster image
    # nrows, ncols = 2, 2  # array of sub-plots
    # figsize = [6, 8]
    # fig, ax = plt.subplots(nrows=nrows, ncols=ncols, figsize=figsize)

    # # plot simple raster image on each sub-plot
    # for i, axi in enumerate(ax.flat):
    #     img = img_4_truth[i]
    #     axi.imshow(img)
    #     axi.set_title(label_truth[i])

    # plt.tight_layout()
    # plt.show()

Loading index for attack samples...
Loading index for real samples...
Using tf.data pipeline for minibatch generation


Generating Minibatches:   0%|          | 1/566 [00:00<05:31,  1.70batch/s]

tf.Tensor([1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0 1 1 0 1 0 0 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   0%|          | 2/566 [00:00<04:04,  2.31batch/s]

tf.Tensor([0 0 0 0 0 0 1 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 1 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:   1%|          | 3/566 [00:01<03:34,  2.63batch/s]

tf.Tensor([0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 1 0 0 1 0 0 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:   1%|          | 4/566 [00:01<03:25,  2.74batch/s]

tf.Tensor([1 0 1 1 1 1 0 1 1 0 1 0 0 0 1 0 0 1 0 1 0 0 0 1 1 0 0 0 0 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   1%|          | 5/566 [00:01<03:21,  2.78batch/s]

tf.Tensor([0 0 0 0 1 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 1 1 0 1 1 1 0 0 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   1%|          | 6/566 [00:02<03:13,  2.90batch/s]

tf.Tensor([1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 1 1 0 1 0 0 1 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   1%|          | 7/566 [00:02<03:09,  2.95batch/s]

tf.Tensor([1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:   1%|▏         | 8/566 [00:02<03:06,  2.99batch/s]

tf.Tensor([1 0 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:   2%|▏         | 9/566 [00:03<03:04,  3.01batch/s]

tf.Tensor([1 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   2%|▏         | 10/566 [00:03<03:04,  3.01batch/s]

tf.Tensor([1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 0 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:   2%|▏         | 11/566 [00:03<03:02,  3.04batch/s]

tf.Tensor([0 1 0 0 1 1 0 1 0 0 0 0 0 1 0 1 1 0 1 1 0 0 0 1 1 0 0 1 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   2%|▏         | 12/566 [00:04<03:00,  3.07batch/s]

tf.Tensor([0 0 1 0 1 1 1 1 0 0 1 0 0 0 1 1 0 1 0 0 1 1 0 0 1 0 0 0 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   2%|▏         | 13/566 [00:04<02:57,  3.11batch/s]

tf.Tensor([1 1 0 1 0 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   2%|▏         | 14/566 [00:04<03:01,  3.05batch/s]

tf.Tensor([0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 1 1 0 0 0 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:   3%|▎         | 15/566 [00:05<03:00,  3.06batch/s]

tf.Tensor([0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   3%|▎         | 16/566 [00:05<03:00,  3.05batch/s]

tf.Tensor([1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   3%|▎         | 17/566 [00:05<03:00,  3.04batch/s]

tf.Tensor([1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 0 1 0 0 0 0 1 0 0 0 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:   3%|▎         | 18/566 [00:06<03:02,  3.00batch/s]

tf.Tensor([1 0 0 1 0 1 1 0 0 1 1 0 0 1 0 0 0 1 0 1 1 0 0 1 1 1 0 1 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   3%|▎         | 19/566 [00:06<02:59,  3.05batch/s]

tf.Tensor([0 0 0 1 0 1 0 1 0 1 1 0 1 1 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   4%|▎         | 20/566 [00:06<02:59,  3.04batch/s]

tf.Tensor([1 1 0 1 1 1 1 1 1 0 0 0 1 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 1 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:   4%|▎         | 21/566 [00:07<03:00,  3.02batch/s]

tf.Tensor([0 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:   4%|▍         | 22/566 [00:07<02:57,  3.06batch/s]

tf.Tensor([1 1 1 1 0 0 1 1 0 1 1 0 1 1 0 0 1 0 1 0 0 0 1 1 1 0 0 0 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:   4%|▍         | 23/566 [00:07<02:56,  3.08batch/s]

tf.Tensor([0 0 1 0 0 1 0 1 1 1 0 0 0 1 0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:   4%|▍         | 24/566 [00:08<02:54,  3.10batch/s]

tf.Tensor([1 0 1 1 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 1 0 1 1 1 1 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:   4%|▍         | 25/566 [00:08<02:53,  3.12batch/s]

tf.Tensor([0 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   5%|▍         | 26/566 [00:08<03:11,  2.83batch/s]

tf.Tensor([0 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   5%|▍         | 27/566 [00:09<03:28,  2.58batch/s]

tf.Tensor([0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 1 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:   5%|▍         | 28/566 [00:09<03:43,  2.41batch/s]

tf.Tensor([1 0 1 1 1 1 1 0 0 1 1 0 1 0 0 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   5%|▌         | 29/566 [00:10<03:48,  2.35batch/s]

tf.Tensor([0 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 1 1 1 0 1 0 1 1 0 1 1 1 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:   5%|▌         | 30/566 [00:10<03:51,  2.32batch/s]

tf.Tensor([0 1 0 1 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:   5%|▌         | 31/566 [00:11<03:55,  2.27batch/s]

tf.Tensor([0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 1 0 0 0 1 1 1 1 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   6%|▌         | 32/566 [00:11<04:03,  2.19batch/s]

tf.Tensor([1 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 0 1 0 1 0 0 0 1 1 1 0 0 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:   6%|▌         | 33/566 [00:12<04:02,  2.20batch/s]

tf.Tensor([0 1 1 0 1 1 1 0 0 1 0 1 1 1 0 1 1 1 1 0 1 0 1 1 0 0 1 1 0 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:   6%|▌         | 34/566 [00:12<03:40,  2.41batch/s]

tf.Tensor([0 1 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   6%|▌         | 35/566 [00:12<03:24,  2.60batch/s]

tf.Tensor([0 1 1 1 0 1 1 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:   6%|▋         | 36/566 [00:13<03:15,  2.71batch/s]

tf.Tensor([0 0 1 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 1 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   7%|▋         | 37/566 [00:13<03:07,  2.82batch/s]

tf.Tensor([1 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0 0 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:   7%|▋         | 38/566 [00:13<03:03,  2.87batch/s]

tf.Tensor([1 1 0 1 1 1 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   7%|▋         | 39/566 [00:14<03:01,  2.90batch/s]

tf.Tensor([1 0 0 0 0 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   7%|▋         | 40/566 [00:14<02:57,  2.96batch/s]

tf.Tensor([1 0 0 1 1 0 1 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   7%|▋         | 41/566 [00:14<02:54,  3.01batch/s]

tf.Tensor([0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:   7%|▋         | 42/566 [00:15<02:51,  3.05batch/s]

tf.Tensor([1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 1 1 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   8%|▊         | 43/566 [00:15<02:50,  3.06batch/s]

tf.Tensor([0 1 0 0 1 1 1 0 0 0 1 1 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 0 1 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:   8%|▊         | 44/566 [00:15<02:51,  3.05batch/s]

tf.Tensor([1 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:   8%|▊         | 45/566 [00:16<02:51,  3.04batch/s]

tf.Tensor([1 0 0 1 0 1 0 1 0 1 0 1 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 1 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:   8%|▊         | 46/566 [00:16<02:49,  3.07batch/s]

tf.Tensor([1 0 0 1 0 1 0 1 1 1 1 0 1 0 1 0 1 1 1 0 1 0 1 0 0 1 0 1 0 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   8%|▊         | 47/566 [00:16<02:47,  3.09batch/s]

tf.Tensor([1 1 0 1 1 0 0 1 0 1 1 1 1 1 1 0 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   8%|▊         | 48/566 [00:16<02:48,  3.08batch/s]

tf.Tensor([1 0 0 0 1 0 0 0 0 0 1 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   9%|▊         | 49/566 [00:17<02:46,  3.11batch/s]

tf.Tensor([1 0 0 1 1 0 1 0 0 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 0 1 1 0 0 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:   9%|▉         | 50/566 [00:17<02:46,  3.10batch/s]

tf.Tensor([0 1 1 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:   9%|▉         | 51/566 [00:17<02:45,  3.11batch/s]

tf.Tensor([1 0 0 1 0 1 1 0 1 1 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 1 1 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   9%|▉         | 52/566 [00:18<02:46,  3.09batch/s]

tf.Tensor([0 1 1 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:   9%|▉         | 53/566 [00:18<02:45,  3.11batch/s]

tf.Tensor([0 0 0 0 1 0 0 1 1 0 1 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  10%|▉         | 54/566 [00:18<02:43,  3.13batch/s]

tf.Tensor([1 1 1 1 1 0 1 0 0 0 1 1 1 0 1 0 1 1 1 1 1 1 1 0 1 0 0 0 1 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  10%|▉         | 55/566 [00:19<02:43,  3.12batch/s]

tf.Tensor([0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 0 1 1 1 0 1 1 1 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  10%|▉         | 56/566 [00:19<02:45,  3.08batch/s]

tf.Tensor([1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0 1 1 0 0 0 1 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  10%|█         | 57/566 [00:19<02:46,  3.06batch/s]

tf.Tensor([1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1 1 0 0 1 0 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  10%|█         | 58/566 [00:20<02:46,  3.06batch/s]

tf.Tensor([1 1 1 0 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 0 1 1 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  10%|█         | 59/566 [00:20<02:44,  3.08batch/s]

tf.Tensor([1 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  11%|█         | 60/566 [00:20<02:41,  3.13batch/s]

tf.Tensor([0 1 1 1 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  11%|█         | 61/566 [00:21<02:42,  3.11batch/s]

tf.Tensor([1 1 0 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 1 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  11%|█         | 62/566 [00:21<02:42,  3.10batch/s]

tf.Tensor([1 0 0 0 0 1 0 1 1 1 0 0 1 1 1 0 0 1 0 0 1 1 0 1 1 0 0 1 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  11%|█         | 63/566 [00:21<02:41,  3.12batch/s]

tf.Tensor([0 1 0 1 0 1 0 1 1 0 0 1 0 1 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  11%|█▏        | 64/566 [00:22<02:48,  2.97batch/s]

tf.Tensor([1 0 1 0 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  11%|█▏        | 65/566 [00:22<03:02,  2.74batch/s]

tf.Tensor([0 0 0 0 1 0 1 0 1 1 0 0 1 1 1 1 0 0 0 1 0 0 1 0 1 1 1 0 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  12%|█▏        | 66/566 [00:23<03:13,  2.58batch/s]

tf.Tensor([0 0 0 0 1 1 1 0 1 1 0 1 1 1 0 1 0 1 1 1 1 0 1 1 0 0 0 0 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  12%|█▏        | 67/566 [00:23<03:22,  2.46batch/s]

tf.Tensor([1 1 0 1 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 0 1 1 0 1 1 1 1 0 1 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  12%|█▏        | 68/566 [00:23<03:24,  2.44batch/s]

tf.Tensor([1 0 1 0 0 1 1 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 1 1 1 0 1 0 1 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  12%|█▏        | 69/566 [00:24<03:30,  2.36batch/s]

tf.Tensor([1 1 0 0 1 1 0 1 1 1 1 1 1 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  12%|█▏        | 70/566 [00:24<03:37,  2.28batch/s]

tf.Tensor([1 0 0 1 0 1 1 1 0 0 0 1 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  13%|█▎        | 71/566 [00:25<03:45,  2.20batch/s]

tf.Tensor([0 0 0 1 1 1 0 1 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 1 0 1 1 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  13%|█▎        | 72/566 [00:25<03:43,  2.21batch/s]

tf.Tensor([1 0 1 0 0 1 0 1 1 0 1 0 1 0 1 0 1 1 1 1 0 0 0 1 0 0 0 1 0 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  13%|█▎        | 73/566 [00:26<03:24,  2.41batch/s]

tf.Tensor([0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  13%|█▎        | 74/566 [00:26<03:11,  2.57batch/s]

tf.Tensor([1 0 0 1 0 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  13%|█▎        | 75/566 [00:26<03:00,  2.73batch/s]

tf.Tensor([0 1 0 1 1 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  13%|█▎        | 76/566 [00:27<02:52,  2.84batch/s]

tf.Tensor([1 0 0 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  14%|█▎        | 77/566 [00:27<02:49,  2.89batch/s]

tf.Tensor([1 0 1 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  14%|█▍        | 78/566 [00:27<02:44,  2.97batch/s]

tf.Tensor([0 1 1 0 0 0 0 1 1 0 0 0 0 1 1 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  14%|█▍        | 79/566 [00:28<02:40,  3.03batch/s]

tf.Tensor([1 0 0 1 1 0 0 0 0 1 0 1 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  14%|█▍        | 80/566 [00:28<02:38,  3.06batch/s]

tf.Tensor([0 0 0 1 0 0 1 1 1 0 1 1 0 0 0 1 1 1 0 0 1 1 0 1 0 1 0 1 1 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  14%|█▍        | 81/566 [00:28<02:36,  3.09batch/s]

tf.Tensor([0 0 1 1 1 1 0 0 0 0 1 0 1 0 1 1 1 0 1 1 0 0 1 1 1 0 1 1 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  14%|█▍        | 82/566 [00:28<02:36,  3.09batch/s]

tf.Tensor([0 0 0 0 1 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 1 1 1 0 0 1 0 0 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  15%|█▍        | 83/566 [00:29<02:35,  3.11batch/s]

tf.Tensor([1 1 0 0 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  15%|█▍        | 84/566 [00:29<02:36,  3.09batch/s]

tf.Tensor([0 1 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  15%|█▌        | 85/566 [00:29<02:34,  3.11batch/s]

tf.Tensor([1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  15%|█▌        | 86/566 [00:30<02:34,  3.12batch/s]

tf.Tensor([0 1 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  15%|█▌        | 87/566 [00:30<02:34,  3.09batch/s]

tf.Tensor([0 0 1 1 1 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 1 0 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  16%|█▌        | 88/566 [00:30<02:34,  3.10batch/s]

tf.Tensor([1 1 0 0 0 1 1 1 0 0 1 1 0 1 1 0 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  16%|█▌        | 89/566 [00:31<02:33,  3.12batch/s]

tf.Tensor([1 1 0 0 0 1 1 1 1 1 0 0 1 0 1 0 0 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  16%|█▌        | 90/566 [00:31<02:34,  3.09batch/s]

tf.Tensor([0 0 0 1 0 1 1 1 1 0 1 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 1 1 0 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  16%|█▌        | 91/566 [00:31<02:35,  3.05batch/s]

tf.Tensor([0 1 1 0 0 0 1 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 1 1 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  16%|█▋        | 92/566 [00:32<02:37,  3.02batch/s]

tf.Tensor([0 1 0 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  16%|█▋        | 93/566 [00:32<02:36,  3.02batch/s]

tf.Tensor([0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 1 0 1 1 1 1 0 0 1 1 0 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  17%|█▋        | 94/566 [00:32<02:34,  3.05batch/s]

tf.Tensor([0 1 0 1 1 1 1 1 0 0 1 1 1 1 0 0 0 1 1 0 1 1 0 1 1 0 1 1 1 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  17%|█▋        | 95/566 [00:33<02:33,  3.07batch/s]

tf.Tensor([1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  17%|█▋        | 96/566 [00:33<02:33,  3.07batch/s]

tf.Tensor([1 0 0 1 0 0 1 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 0 0 0 0 1 1 0 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  17%|█▋        | 97/566 [00:33<02:31,  3.09batch/s]

tf.Tensor([1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 1 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  17%|█▋        | 98/566 [00:34<02:31,  3.08batch/s]

tf.Tensor([1 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  17%|█▋        | 99/566 [00:34<02:31,  3.07batch/s]

tf.Tensor([0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  18%|█▊        | 100/566 [00:34<02:30,  3.11batch/s]

tf.Tensor([1 1 0 1 0 1 1 1 0 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  18%|█▊        | 101/566 [00:35<02:29,  3.11batch/s]

tf.Tensor([1 0 0 0 1 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  18%|█▊        | 102/566 [00:35<02:28,  3.13batch/s]

tf.Tensor([1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  18%|█▊        | 103/566 [00:35<02:33,  3.01batch/s]

tf.Tensor([1 1 1 1 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 0 0 0 1 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  18%|█▊        | 104/566 [00:36<02:47,  2.75batch/s]

tf.Tensor([1 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 1 1 1 0 0 1 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  19%|█▊        | 105/566 [00:36<03:01,  2.54batch/s]

tf.Tensor([0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  19%|█▊        | 106/566 [00:37<03:10,  2.42batch/s]

tf.Tensor([0 0 1 1 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 0 1 0 0 1 0 0 1 0 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  19%|█▉        | 107/566 [00:37<03:14,  2.36batch/s]

tf.Tensor([1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 1 0 0 0 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  19%|█▉        | 108/566 [00:38<03:16,  2.33batch/s]

tf.Tensor([0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 1 1 1 0 0 1 0 0 1 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  19%|█▉        | 109/566 [00:38<03:19,  2.29batch/s]

tf.Tensor([0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 1 1 1 1 0 1 1 0 0 0 1 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  19%|█▉        | 110/566 [00:39<03:26,  2.21batch/s]

tf.Tensor([1 1 0 0 1 1 1 1 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  20%|█▉        | 111/566 [00:39<03:29,  2.17batch/s]

tf.Tensor([1 1 0 0 1 1 1 1 1 0 0 1 1 0 1 0 1 1 0 1 0 1 1 1 0 1 1 0 1 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  20%|█▉        | 112/566 [00:39<03:12,  2.35batch/s]

tf.Tensor([0 1 1 0 0 1 1 1 0 0 0 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  20%|█▉        | 113/566 [00:40<02:57,  2.55batch/s]

tf.Tensor([1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 1 0 0 1 1 0 0 1 0 0 1 0 0 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  20%|██        | 114/566 [00:40<02:47,  2.71batch/s]

tf.Tensor([1 1 0 1 0 1 0 1 1 1 1 1 1 0 0 0 0 1 1 0 1 1 0 0 0 0 0 1 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  20%|██        | 115/566 [00:40<02:40,  2.81batch/s]

tf.Tensor([0 1 1 1 0 0 0 1 1 1 0 0 1 1 0 0 0 0 0 1 1 1 1 1 0 0 1 1 0 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  20%|██        | 116/566 [00:41<02:34,  2.91batch/s]

tf.Tensor([0 1 0 1 0 1 0 0 1 1 0 1 0 0 1 1 1 0 1 0 0 0 0 1 0 0 1 0 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  21%|██        | 117/566 [00:41<02:31,  2.96batch/s]

tf.Tensor([0 1 1 1 0 0 1 1 1 1 0 1 1 1 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  21%|██        | 118/566 [00:41<02:29,  3.00batch/s]

tf.Tensor([0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 0 0 0 1 0 1 1 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  21%|██        | 119/566 [00:42<02:26,  3.05batch/s]

tf.Tensor([1 1 1 1 1 0 0 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0 0 0 1 0 0 0 0 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  21%|██        | 120/566 [00:42<02:25,  3.07batch/s]

tf.Tensor([1 1 1 0 0 1 0 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 1 1 0 1 1 1 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  21%|██▏       | 121/566 [00:42<02:23,  3.10batch/s]

tf.Tensor([0 1 1 1 1 0 0 0 0 1 0 0 1 0 1 0 1 1 1 1 0 0 1 1 1 0 1 1 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  22%|██▏       | 122/566 [00:43<02:24,  3.06batch/s]

tf.Tensor([1 1 1 1 0 1 1 0 1 0 1 1 1 0 1 1 0 1 1 0 0 0 0 1 1 1 1 1 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  22%|██▏       | 123/566 [00:43<02:23,  3.08batch/s]

tf.Tensor([0 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 0 0 1 1 1 1 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  22%|██▏       | 124/566 [00:43<02:23,  3.09batch/s]

tf.Tensor([0 0 1 0 0 1 1 0 1 1 1 0 1 0 0 0 1 1 1 0 1 1 1 1 0 0 1 0 1 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  22%|██▏       | 125/566 [00:44<02:23,  3.08batch/s]

tf.Tensor([1 0 1 1 1 0 1 0 1 0 0 0 1 0 1 0 0 1 1 1 1 1 1 0 0 0 0 0 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  22%|██▏       | 126/566 [00:44<02:21,  3.10batch/s]

tf.Tensor([0 0 0 1 1 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 1 1 1 1 0 0 1 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  22%|██▏       | 127/566 [00:44<02:20,  3.13batch/s]

tf.Tensor([0 1 1 0 1 1 0 1 1 1 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  23%|██▎       | 128/566 [00:44<02:21,  3.10batch/s]

tf.Tensor([0 1 0 1 1 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 1 0 1 1 0 1 1 0 0 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  23%|██▎       | 129/566 [00:45<02:21,  3.10batch/s]

tf.Tensor([0 0 1 0 1 0 0 0 1 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 0 1 0 0 0 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  23%|██▎       | 130/566 [00:45<02:20,  3.10batch/s]

tf.Tensor([0 0 0 1 1 1 0 0 1 1 0 0 1 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 0 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  23%|██▎       | 131/566 [00:45<02:21,  3.09batch/s]

tf.Tensor([1 1 0 0 0 1 0 1 1 1 1 0 0 1 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  23%|██▎       | 132/566 [00:46<02:20,  3.09batch/s]

tf.Tensor([0 1 0 1 0 0 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  23%|██▎       | 133/566 [00:46<02:19,  3.10batch/s]

tf.Tensor([1 1 1 1 0 1 1 1 0 0 1 1 1 0 0 0 1 0 1 1 1 0 0 1 1 1 1 0 0 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  24%|██▎       | 134/566 [00:46<02:20,  3.08batch/s]

tf.Tensor([1 0 0 1 0 1 0 1 0 1 0 0 1 1 1 0 1 0 1 0 1 1 1 0 0 1 1 0 1 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  24%|██▍       | 135/566 [00:47<02:19,  3.09batch/s]

tf.Tensor([1 0 0 1 0 1 0 0 0 1 0 1 0 1 1 1 0 1 0 1 0 0 1 1 1 0 0 0 0 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  24%|██▍       | 136/566 [00:47<02:18,  3.11batch/s]

tf.Tensor([0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 1 1 1 1 0 1 1 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  24%|██▍       | 137/566 [00:47<02:16,  3.13batch/s]

tf.Tensor([0 0 1 1 0 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 1 1 1 0 0 1 1 0 0 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  24%|██▍       | 138/566 [00:48<02:18,  3.10batch/s]

tf.Tensor([0 0 1 0 1 1 1 1 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 1 1 1 1 1 0 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  25%|██▍       | 139/566 [00:48<02:17,  3.10batch/s]

tf.Tensor([0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 1 1 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  25%|██▍       | 140/566 [00:48<02:16,  3.12batch/s]

tf.Tensor([1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 1 1 1 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  25%|██▍       | 141/566 [00:49<02:16,  3.11batch/s]

tf.Tensor([0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  25%|██▌       | 142/566 [00:49<02:16,  3.11batch/s]

tf.Tensor([1 0 0 1 1 1 0 1 0 0 0 1 0 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  25%|██▌       | 143/566 [00:49<02:26,  2.88batch/s]

tf.Tensor([1 1 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  25%|██▌       | 144/566 [00:50<02:40,  2.62batch/s]

tf.Tensor([1 1 1 1 0 1 1 0 0 0 0 1 0 1 1 0 1 1 0 0 1 1 0 1 1 0 0 1 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  26%|██▌       | 145/566 [00:50<02:50,  2.47batch/s]

tf.Tensor([1 0 0 0 1 1 0 1 0 1 1 0 0 1 1 1 0 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  26%|██▌       | 146/566 [00:51<02:57,  2.37batch/s]

tf.Tensor([0 1 1 0 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  26%|██▌       | 147/566 [00:51<02:59,  2.34batch/s]

tf.Tensor([0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 1 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  26%|██▌       | 148/566 [00:52<03:06,  2.24batch/s]

tf.Tensor([0 1 0 1 0 0 0 1 1 0 1 1 1 1 0 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  26%|██▋       | 149/566 [00:52<03:09,  2.20batch/s]

tf.Tensor([0 0 0 1 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 0 0 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  27%|██▋       | 150/566 [00:53<03:13,  2.16batch/s]

tf.Tensor([0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 1 1 1 0 1 1 0 0 1 0 0 1 0 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  27%|██▋       | 151/566 [00:53<02:58,  2.33batch/s]

tf.Tensor([1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  27%|██▋       | 152/566 [00:53<02:44,  2.52batch/s]

tf.Tensor([0 1 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0 1 1 1 0 0 0 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  27%|██▋       | 153/566 [00:54<02:35,  2.66batch/s]

tf.Tensor([0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 1 1 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  27%|██▋       | 154/566 [00:54<02:27,  2.79batch/s]

tf.Tensor([1 0 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  27%|██▋       | 155/566 [00:54<02:22,  2.88batch/s]

tf.Tensor([0 1 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 0 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  28%|██▊       | 156/566 [00:55<02:18,  2.95batch/s]

tf.Tensor([1 0 0 1 1 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 1 0 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  28%|██▊       | 157/566 [00:55<02:17,  2.97batch/s]

tf.Tensor([0 0 1 0 1 0 0 1 1 0 1 1 0 1 0 1 0 1 1 0 1 0 1 0 0 1 1 0 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  28%|██▊       | 158/566 [00:55<02:14,  3.02batch/s]

tf.Tensor([1 1 1 0 1 1 1 0 0 1 0 0 0 0 1 0 0 1 1 1 1 1 0 0 0 1 1 1 1 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  28%|██▊       | 159/566 [00:56<02:13,  3.05batch/s]

tf.Tensor([0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  28%|██▊       | 160/566 [00:56<02:14,  3.02batch/s]

tf.Tensor([1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  28%|██▊       | 161/566 [00:56<02:12,  3.06batch/s]

tf.Tensor([1 1 1 0 1 0 1 0 0 1 0 1 1 0 1 1 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  29%|██▊       | 162/566 [00:57<02:12,  3.06batch/s]

tf.Tensor([0 0 1 1 1 0 1 0 1 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 1 1 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  29%|██▉       | 163/566 [00:57<02:11,  3.07batch/s]

tf.Tensor([0 1 1 0 1 1 0 0 1 1 1 1 1 0 0 0 0 1 1 0 0 0 0 0 1 1 0 1 0 1 1 0], shape=(32,), dtype=int64)


Generating Minibatches:  29%|██▉       | 164/566 [00:57<02:09,  3.11batch/s]

tf.Tensor([0 0 0 1 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 1 1 1 0 0 1 1 0 1 0 0], shape=(32,), dtype=int64)


Generating Minibatches:  29%|██▉       | 165/566 [00:58<02:08,  3.12batch/s]

tf.Tensor([0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 1 0 0 1], shape=(32,), dtype=int64)


Generating Minibatches:  29%|██▉       | 166/566 [00:58<02:07,  3.13batch/s]

tf.Tensor([1 1 0 1 1 0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 1 0 1 1], shape=(32,), dtype=int64)


Generating Minibatches:  30%|██▉       | 167/566 [00:58<02:20,  2.85batch/s]

tf.Tensor([1 0 0 1 0 1 0 0 0 0 0 0 1 1 0 1 1 1 1 1 1 0 1 0 0 1 0 1 0 1 1 1], shape=(32,), dtype=int64)


InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Error in user-defined function passed to ParallelMapDatasetV2:23 transformation with iterator: Iterator::Root::Prefetch::MapAndBatch::ParallelMapV2: jpeg::Uncompress failed. Invalid JPEG data or crop window.
	 [[{{node DecodeJpeg}}]] [Op:IteratorGetNext] name: 

In [9]:
import tensorflow as tf
from tensorflow import keras
import math

# Print available physical devices
print(tf.config.experimental.list_physical_devices())

def get_model():
    # Load VGG16 with pre-trained weights and without the top layer
    vgg16 = tf.keras.applications.VGG16(
        include_top=False,
        weights="imagenet",
        input_shape=(224, 224, 3)
    )
    for layer in vgg16.layers:
        layer.trainable = False
    # Extract the output from the last layer of VGG16
    last_output = vgg16.output
    x = keras.layers.Flatten()(last_output)
    share_weight_net = keras.Model(inputs=vgg16.input, outputs=x)
    print(share_weight_net.summary())

    # Define inputs
    as_input = keras.Input(shape=(224, 224, 3), name="as_input")
    lpc_input_1 = keras.Input(shape=(224, 224, 3), name="lpc_input_1")
    lpc_input_2 = keras.Input(shape=(224, 224, 3), name="lpc_input_2")

    # Anti-spoofing branch
    as_flatten_1 = share_weight_net(as_input)
    as_fc1 = keras.layers.Dense(1024, activation="relu", name="as_fc1")(as_flatten_1)
    as_fc2 = keras.layers.Dense(1024, activation="relu", name="as_fc2")(as_fc1)
    as_output = keras.layers.Dense(2, activation='softmax', name="as_output")(as_fc2)

    # Uncomment and complete if needed
    #Local patch comparison branch
    lpc_flatten_1 = share_weight_net(lpc_input_1)
    lpc_fc_o1 = keras.layers.Dense(1024, activation="relu", name="lpc_fc1")(lpc_flatten_1)

    lpc_flatten_2 = share_weight_net(lpc_input_2)
    lpc_fc_o2 = keras.layers.Dense(1024, activation="relu", name="lpc_fc2")(lpc_flatten_2)

    lpc = keras.layers.Lambda(lambda x: tf.math.square(x[0] - x[1]), name='lpc')([lpc_fc_o1, lpc_fc_o2])

    # Define the model
    model = keras.Model(
        inputs=[as_input,lpc_input_1,lpc_input_2],
        outputs=[as_output,lpc]
    )

    # Compile the model with appropriate losses and metrics
    model.compile(
        optimizer='adam',
        loss={
            "as_output": keras.losses.SparseCategoricalCrossentropy(),
            "lpc": tpc_loss},
        loss_weights={
            "as_output": 1.0,
            "lpc": 2.5*math.exp(-5)
        },
        metrics={"as_output": 'accuracy'}
    )

    return model

def tpc_loss(y_true, y_pred):
    return tf.reduce_sum(y_pred, axis=1, keepdims=True)

if __name__ == '__main__':
    model = get_model()
    model.summary()
    #Uncomment to plot model architecture
    tf.keras.utils.plot_model(
        model,
        to_file='model1.png',
        show_shapes=True,
        show_dtype=False,
        show_layer_names=True,
        rankdir='TB',
        expand_nested=False,
        dpi=200,
        show_layer_activations=True,
    )

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)           │ (None, 224, 224, 3)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block1_conv1 (Conv2D)                │ (None, 224, 224, 64)        │           1,792 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block1_conv2 (Conv2D)                │ (None, 224, 224, 64)        │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block1_pool (MaxPooling2D)           │ (None, 112, 112, 64)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block2_conv1 (Conv2D)                │ (None, 112, 112, 128)       │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block2_conv2 (Conv2D)                │ (None, 112, 112, 128)       │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block2_pool (MaxPooling2D)           │ (None, 56, 56, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block3_conv1 (Conv2D)                │ (None, 56, 56, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block3_conv2 (Conv2D)                │ (None, 56, 56, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block3_conv3 (Conv2D)                │ (None, 56, 56, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block3_pool (MaxPooling2D)           │ (None, 28, 28, 256)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block4_conv1 (Conv2D)                │ (None, 28, 28, 512)         │       1,180,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block4_conv2 (Conv2D)                │ (None, 28, 28, 512)         │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block4_conv3 (Conv2D)                │ (None, 28, 28, 512)         │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block4_pool (MaxPooling2D)           │ (None, 14, 14, 512)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block5_conv1 (Conv2D)                │ (None, 14, 14, 512)         │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block5_conv2 (Conv2D)                │ (None, 14, 14, 512)         │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block5_conv3 (Conv2D)                │ (None, 14, 14, 512)         │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block5_pool (MaxPooling2D)           │ (None, 7, 7, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_2 (Flatten)                  │ (None, 25088)               │               0 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 14,714,688 (56.13 MB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 14,714,688 (56.13 MB)

None


Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ as_input (InputLayer)     │ (None, 224, 224, 3)    │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ functional_4 (Functional) │ (None, 25088)          │     14,714,688 │ as_input[0][0],        │
│                           │                        │                │ lpc_input_1[0][0],     │
│                           │                        │                │ lpc_input_2[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ lpc_input_1 (InputLayer)  │ (None, 224, 224, 3)    │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ lpc_input_2 (InputLayer)  │ (None, 224, 224, 3)    │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ as_fc1 (Dense)            │ (None, 1024)           │     25,691,136 │ functional_4[0][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ as_fc2 (Dense)            │ (None, 1024)           │      1,049,600 │ as_fc1[0][0]           │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ lpc_fc1 (Dense)           │ (None, 1024)           │     25,691,136 │ functional_4[1][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ lpc_fc2 (Dense)           │ (None, 1024)           │     25,691,136 │ functional_4[2][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ as_output (Dense)         │ (None, 2)              │          2,050 │ as_fc2[0][0]           │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ lpc (Lambda)              │ (None, 1024)           │              0 │ lpc_fc1[0][0],         │
│                           │                        │                │ lpc_fc2[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 92,839,746 (354.16 MB)

 Trainable params: 78,125,058 (298.02 MB)

 Non-trainable params: 14,714,688 (56.13 MB)

In [ ]:
import tensorflow as tf
import numpy as np
import os
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from tqdm import tqdm

# Configure GPU memory growth (if needed)
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e:
        print(e)

if __name__ == '__main__':
    # with open("E:/akash singh/GFA-CNN-new/GFA-CNN-master/GFA-CNN-master/config.yaml", "r") as ymlfile:
    #     cfg = yaml.safe_load(ymlfile)  # Use safe_load for security

    epoch = 2 #cfg['training']['epoch']
    batch = 32# cfg['training']['batch']

    attack_dir = r"/content/extracted_files/dataset_small/msumsfd_gfacnn/attack"
    real_dir = r"/content/extracted_files/dataset_small/msumsfd_gfacnn/real"
    dataset = Dataset('MSU-MSFD', batch_size=batch, attack_dir=attack_dir, real_dir=real_dir)
    GFA_CNN = get_model()

    checkpoint_filepath = './checkpoints/chkpt.weights.h5'
    model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
        filepath=checkpoint_filepath,
        save_weights_only=True,
        monitor='loss',
        mode='min',
        save_best_only=True)

    print('Preprocessing data ...')

    print('Training ...')
    j = 1
    for e in tqdm(range(epoch), desc='Epochs'):
        print(f"[epoch number: {j}]")
        dataset.shuffle_dataset()
        i = 1
        for batch_img_4_truth, batch_label_truth, batch_img_random_1, batch_img_random_2, batch_label_random in tqdm(
                dataset.generate_minibatch(), desc='Batches', total=len(dataset.list_file_path_truth) // batch):
            GFA_CNN.fit(
                {"as_input": batch_img_4_truth, "lpc_input_1": batch_img_random_1, "lpc_input_2": batch_img_random_2},
                {"as_output": batch_label_truth, 'lpc': batch_label_random},
                epochs=4,
                batch_size=16,
                callbacks=[model_checkpoint_callback],
                verbose=1
            )
            print(f"counting iterations {i}")
            i += 1
        j += 1

    # print("Saving the model...")
    # model_save_path = '/content/model_saved'
    # GFA_CNN.save(model_save_path)
    # print(f"Model saved to {model_save_path}")

    # Load the testing dataset
    attack_dir_test = r"/content/extracted_files/dataset_small/msumsfd_gfacnn_test/attack"
    real_dir_test = r"/content/extracted_files/dataset_small/msumsfd_gfacnn_test/real"
    test_dataset = Dataset('MSU-MSFD', batch_size=batch, attack_dir=attack_dir_test, real_dir=real_dir_test)

    y_true = []
    y_pred = []

    for batch_img_4_truth, batch_label_truth, batch_img_random_1, batch_img_random_2 in test_dataset.generate_minibatch():
        predictions = GFA_CNN.predict({
            "as_input": batch_img_4_truth,
            "lpc_input_1": batch_img_random_1,
            "lpc_input_2": batch_img_random_2
        })

        y_true.extend(batch_label_truth)
        y_pred.extend(predictions[0])  # Adjust according to your output names

    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    y_pred = y_pred[:, 0]  # Assuming first column represents positive class probability

    def calculate_eer(y_true, y_pred):
        fpr, tpr, thresholds = roc_curve(y_true, y_pred)
        fnr = 1 - tpr
        eer_threshold = thresholds[np.nanargmin(np.abs(fnr - fpr))]
        eer = fpr[np.nanargmin(np.abs(fnr - fpr))]
        return eer

    def calculate_hter(eer, y_true, y_pred):
        fpr, tpr, _ = roc_curve(y_true, y_pred)
        fnr = 1 - tpr
        threshold = np.interp(eer, fpr, tpr)
        hter = (fpr[np.argmin(np.abs(threshold - tpr))] + fnr[np.argmin(np.abs(threshold - fnr))]) / 2
        return hter

    eer = calculate_eer(y_true, y_pred)
    print(f"Equal Error Rate (EER): {eer:.4f}")

    hter = calculate_hter(eer, y_true, y_pred)
    print(f"Half Total Error Rate (HTER): {hter:.4f}")

    fpr, tpr, thresholds = roc_curve(y_true, y_pred)
    plt.figure()
    plt.plot(fpr, tpr, color='blue', lw=2, label='ROC curve (area = %0.2f)' % auc(fpr, tpr))
    plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate (FPR)')
    plt.ylabel('True Positive Rate (TPR)')
    plt.title('Receiver Operating Characteristic (ROC)')
    plt.legend(loc='lower right')
    plt.grid(True)
    plt.show()

Loading index for attack samples...
Loading index for real samples...


Model: "functional_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)           │ (None, 224, 224, 3)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block1_conv1 (Conv2D)                │ (None, 224, 224, 64)        │           1,792 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block1_conv2 (Conv2D)                │ (None, 224, 224, 64)        │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block1_pool (MaxPooling2D)           │ (None, 112, 112, 64)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block2_conv1 (Conv2D)                │ (None, 112, 112, 128)       │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block2_conv2 (Conv2D)                │ (None, 112, 112, 128)       │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block2_pool (MaxPooling2D)           │ (None, 56, 56, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block3_conv1 (Conv2D)                │ (None, 56, 56, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block3_conv2 (Conv2D)                │ (None, 56, 56, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block3_conv3 (Conv2D)                │ (None, 56, 56, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block3_pool (MaxPooling2D)           │ (None, 28, 28, 256)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block4_conv1 (Conv2D)                │ (None, 28, 28, 512)         │       1,180,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block4_conv2 (Conv2D)                │ (None, 28, 28, 512)         │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block4_conv3 (Conv2D)                │ (None, 28, 28, 512)         │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block4_pool (MaxPooling2D)           │ (None, 14, 14, 512)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block5_conv1 (Conv2D)                │ (None, 14, 14, 512)         │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block5_conv2 (Conv2D)                │ (None, 14, 14, 512)         │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block5_conv3 (Conv2D)                │ (None, 14, 14, 512)         │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block5_pool (MaxPooling2D)           │ (None, 7, 7, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_3 (Flatten)                  │ (None, 25088)               │               0 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 14,714,688 (56.13 MB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 14,714,688 (56.13 MB)

None
Preprocessing data ...
Training ...


Epochs:   0%|          | 0/2 [00:00<?, ?it/s]

[epoch number: 1]



Batches:   0%|          | 0/35 [00:00<?, ?it/s]

Using tf.data pipeline for minibatch generation




Generating Minibatches:   0%|          | 0/36 [00:00<?, ?batch/s]

Generating Minibatches:   3%|▎         | 1/36 [00:00<00:24,  1.44batch/s]

Epoch 1/4
